services:
    cyberuserbot:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cyberuserbot
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - default

networks:
    default:
        external: false
